print error message before exit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,5 +11,6 @@ jobs:
              then
                 echo "test.txt found!";
              else
-                raise error "test.txt missing!";
+                echo "test.txt missing!";
+                exit 123;
              fi
